name: Build

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

env: 
  version_number: 1.${{ github.ref_name }}.${{ github.run_number}}

jobs:

  createrelease:
    name: Create Release
    runs-on: [ubuntu-latest] 
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.version_number }}
        release_name: Release ${{ env.version_number }}
        draft: false
        prerelease: false
    - name: Get Chromedriver Version
      id: chromedriver_win64_url
      run: |
        chromedriver_win64_url=$(curl https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json | jq -r '.["channels"]["Stable"]["downloads"]["chromedriver"][] | select(.platform == "win64") | .url')
        echo "chromedriver_win64_url=$chromedriver_win64_url" >> $GITHUB_OUTPUT
        cat $GITHUB_OUTPUT
    - name: Save Chromedriver Version
      uses: actions/upload-artifact@v4
      with:
        name: chromedriver_win64_url
        path: chromedriver_win64_url.txt
        
  build_osx:
    name: Build OSX
    needs: createrelease
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build with pyinstaller
      run: >
        echo "Version number: $version_number" &&
        url=$(curl https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json | jq -r '.["channels"]["Stable"]["downloads"]["chromedriver"][] | select(.platform == "mac-arm64") | .url') &&
        echo $url &&
        pushd ext/OSX &&
        curl $url -o chromedriver-mac-arm64.zip &&
        unzip -j chromedriver-mac-arm64.zip &&
        popd &&
        pyinstaller Trimmer.spec --clean -y &&
        cd dist/ &&
        df -h &&
        hdiutil create ./Trimmer-$version_number-Mac64.dmg -srcfolder Trimmer.app -ov -size 400M
    - name: Upload Release Asset
      id: upload-release-asset
      uses: softprops/action-gh-release@v2
      with:
        files: ./dist/Trimmer-${{ env.version_number }}-Mac64.dmg

  build_win:
    name: Build Win-64
    needs: createrelease
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build with pyinstaller
      shell: cmd
      run: |
        echo "Version number: %version_number% "
        dir
        echo "%chromedriver_win64_url%"
        pushd ext\Win64
        curl -O %chromedriver_win64_url%
        dir
        7z e .\chromedriver_win32.zip
        dir
        popd
        pyinstaller Trimmer.spec --clean -y
        cd inno/
        "%ProgramFiles(x86)%\Inno Setup 6\ISCC.exe" Trimmer.iss
    - name: Upload Release Asset
      id: upload-release-asset
      uses: softprops/action-gh-release@v2
      with:
        asset_path: ./inno/Output/Trimmer-${{ env.version_number }}-Win64.exe
